apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-api-deployment
  labels:
    app: metrics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-api
  template:
    metadata:
      labels:
        app: metrics-api
    spec:
      containers:
      - name: metrics-api
        image: {{ .Values.image }}
        env:
        - name: KAFKA_HOST
          value: {{ .Values.kafka.host }}
        - name: KAFKA_PORT
          value: "{{ .Values.kafka.port }}"
        resources:
          limits:
            cpu: 100m
            memory: 64Mi