apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metrics-api
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/cluster-issuer: selfsigning-issuer
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
        - path: /
          backend:
            serviceName: metrics-api
            servicePort: 80
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: metrics-api-cert