apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metrics-api
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
        - path: /
          backend:
            serviceName: metrics-api
            servicePort: 80