apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakfa-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: {{ .Values.kafka.image }}
        env:
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: {{ .Values.kafka.host }}
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: {{ .Values.zookeeper.host }}:{{ .Values.zookeeper.port }}
        ports:
        - containerPort: 9092