apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redis-commander
  annotations:
    cert-manager.io/cluster-issuer: selfsigning-issuer
spec:
  rules:
  - host: {{ .Values.redis_commander.hostname }}
    http:
      paths:
        - path: /
          backend:
            serviceName: redis-commander
            servicePort: 80
  tls:
  - hosts:
    - {{ .Values.redis_commander.hostname }}
    secretName: redis-cert