apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.host }}
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: {{ .Values.zookeeper.port }}
      targetPort: 2181