apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: color-viewer
  annotations:
    cert-manager.io/cluster-issuer: selfsigning-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
        - path: /
          backend:
            serviceName: color-viewer
            servicePort: 443
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: color-viewer-cert