apiVersion: apps/v1
kind: Deployment
metadata:
  name: parrot-deployment
  labels:
    app: parrot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parrot
  template:
    metadata:
      labels:
        app: parrot
    spec:
      containers:
      - name: parrot
        image: {{ .Values.image }}
        env:
        - name: KAFKA_HOST
          value: {{ .Values.kafka.host }}
        - name: KAFKA_PORT
          value: "{{ .Values.kafka.port }}"
        resources:
          limits:
            cpu: 100m
            memory: 64Mi