kafka:
  image: wurstmeister/kafka
  host: kafka
  port: 9092

zookeeper:
  image: wurstmeister/zookeeper
  host: zookeeper
  port: 2181

redis:
  image: redis:5.0-alpine
  host: redis
  port: 6379

redis_commander:
  image: rediscommander/redis-commander
  hostname: redis.ponglehub.co.uk

parrot:
  kafka:
    host: kafka
    port: 9092

producer:
  image: benwright/kafka-producer
  kafka:
    host: kafka
    port: 9092

color-loader:
  image: benwright/kafka-color-loader

color-viewer:
  image: benwright/kafka-color-viewer
  hostname: color-viewer.ponglehub.co.uk

metrics-api:
  kafka:
    host: kafka
    port: 9092
  redis:
    host: redis
    port: 6379